export default dataResume = {
  name: 'Andrii Sereda',
  profesion: 'Front-End Developer, Hardware developer',
  description: `Full cycle of device development, microcontroller firmware, printed
        circuit boards of devices, design and development of radio component
        cases. Website development and support.`,
  contacts: [
    {
      name: 'telephone',
      shotName: 'T:',
      title: '+3-8-067-621-00-56',
      href: 'tel:+380676210056',
    },
    {
      name: 'email',
      shotName: 'M:',
      title: 'a.a.sereda@ukr.net',
      href: 'mailto:a.a.sereda@ukr.net',
    },
    {
      name: 'web-site',
      shotName: 'S:',
      title: 'resume web site',
      href: 'http://195.72.145.106',
    },
  ],
  experienceProject: [
    {
      id: 1,
      name: 'Incubator control unit v5.0.4',
      tech: ['C++', 'ArduinoIDE'],
      link: 'https://github.com/SeredaAndrey/rab_prog_incubator_V5_0_4',
    },
    {
      id: 2,
      name: 'Incubator control unit V6.2 mini',
      tech: ['C++', 'ArduinoIDE'],
      link: 'https://github.com/SeredaAndrey/rab_prog_incubator_V6_2_mini_NOT_PID_engl',
    },
    {
      id: 3,
      name: 'Underfloor heating controller v2.0 with MQTT',
      tech: ['C++', 'ArduinoIDE'],
      link: 'https://github.com/SeredaAndrey/controller_hot_flore-v2.0-with-MQTT',
    },
    {
      id: 4,
      name: 'Boller controller v2.0 with MQTT',
      tech: ['C++', 'ArduinoIDE', 'HTML'],
      link: 'https://github.com/SeredaAndrey/controller_for_boller-v2.0-with-MQTT-and-DS18b20',
    },
    {
      id: 5,
      name: 'Room temperature controller v2.0 with MQTT TM1637',
      tech: ['C++', 'ArduinoIDE', 'HTML'],
      link: 'https://github.com/SeredaAndrey/room-controller-v2.0-with-MQTT-DS18b20-and-TM1637',
    },
    {
      id: 6,
      name: 'Room temperature controller v2.0 with MQTT OLED',
      tech: ['C++', 'ArduinoIDE', 'HTML'],
      link: 'https://github.com/SeredaAndrey/room_controller-v2.0-with-MQTT-DS18b20-and-OLED',
    },
    {
      id: 7,
      name: 'Radiator controller v2.0 with MQTT',
      tech: ['C++', 'ArduinoIDE', 'HTML'],
      link: 'https://github.com/SeredaAndrey/hot-panel-v2.0-with-MQTT-with-MQTTcontroling',
    },
  ],
  experienceWork: [
    {
      id: 8,
      nameCompany: `LCC "LMMP"`,
      position: 'PM. Chief Engineer Project',
      startDurationWork: 'April 2022',
      endDurationWork: 'up to now',
      city: 'Lviv',
      country: 'Ukraine',
      responsibilities: [
        'Design team management',
        'Maintenance of construction documentation',
      ],
    },
    {
      id: 7,
      nameCompany: `LCC "DEAS Construction"`,
      position: 'Civil Engineer, Chief Engineer',
      startDurationWork: 'August 2021',
      endDurationWork: 'April 2022',
      city: 'Mariupol',
      country: 'Ukraine',
      responsibilities: [
        'Design team management',
        'Maintenance of construction documentation',
        'Company management',
      ],
    },
    {
      id: 6,
      nameCompany: `LCC "AZOVTECHGAZ"`,
      position: 'Civil engineer, designer of the POB group',
      startDurationWork: 'July 2020',
      endDurationWork: 'August 2021',
      city: 'Mariupol',
      country: 'Ukraine',
      responsibilities: [
        'Development of project documentation in the field of preparation for production',
      ],
    },
    {
      id: 5,
      nameCompany: `LCC "MBK"PROMBUDSERVICE"`,
      position: 'Technical director, Director',
      startDurationWork: 'April 2019',
      endDurationWork: 'July 2019',
      city: 'Kyiv',
      country: 'Ukraine',
      responsibilities: [
        'Construction site management',
        'Maintenance of construction documentation',
        'Company management',
      ],
    },
    {
      id: 4,
      nameCompany: `LCC "TONDO"`,
      position: 'Head of production and technical department',
      startDurationWork: 'November 2010',
      endDurationWork: 'April 2019',
      city: 'Mariupol',
      country: 'Ukraine',
      responsibilities: [
        'Conducting construction projects',
        'Maintaining project documentation',
        'Maintaining budget documentation',
        'Department management',
      ],
    },
    {
      id: 3,
      nameCompany: `Building hypermarket OBI`,
      position: 'Head of the warehouse and product display of the hypermarket',
      startDurationWork: 'October 2009',
      endDurationWork: 'September 2010',
      city: 'Mariupol',
      country: 'Ukraine',
      responsibilities: [
        'Personnel management of the product display department',
        'Personnel management of the goods acceptance department',
        'Maintaining warehouse documentation',
      ],
    },
    {
      id: 2,
      nameCompany: `LCC "StroyAsovService LTD"`,
      position: 'Head of the construction site, Chief Engineer, Director',
      startDurationWork: 'February 2003',
      endDurationWork: 'March 2009',
      city: 'Mariupol',
      country: 'Ukraine',
      responsibilities: [
        'Construction site management',
        'Maintenance of construction documentation',
        'Company management',
      ],
    },
    {
      id: 1,
      nameCompany: `LCC "MKS"`,
      position: 'Service engineer repair engineer',
      startDurationWork: 'November 2001',
      endDurationWork: 'February 2003',
      city: 'Kharkiv',
      country: 'Ukraine',
      responsibilities: [
        'Repair of office equipment',
        'Software installation and configuration',
      ],
    },
  ],
  education: [
    {
      id: 1,
      name: 'Priasov State Technical University (PSTU)',
      profession: 'Сivil engineer, industrial civil engineering',
      startDurationEdu: 'September 1996',
      endDurationEdu: 'June 2002',
      country: 'Ukraine',
      city: 'Mariupol',
    },
    {
      id: 2,
      name: 'EDU.GENIUS.SPACE',
      profession: 'Profession Project manager 10.0',
      startDurationEdu: 'May 2022',
      endDurationEdu: 'June 2022',
      country: 'Ukraine',
      city: 'Lviv',
    },
    {
      id: 3,
      name: 'GoIT',
      profession: 'Full stack developer. HTML+CSS 1.0',
      startDurationEdu: 'June 2022',
      endDurationEdu: 'August 2022',
      country: 'Ukraine',
      city: 'Lviv',
    },
    {
      id: 4,
      name: 'GoIT',
      profession: 'Full stack developer. JavaScript 2.0',
      startDurationEdu: 'August 2022',
      endDurationEdu: 'November 2022',
      country: 'Ukraine',
      city: 'Lviv',
    },
  ],
  skils: {
    tech: [
      'HTML, CSS (SCSS)',
      'GIT',
      'WebPack, Parcel',
      'JavaScript',
      'React.js',
      'Node.js',
      'C++ (ArduinoIDE)',
      'Spring Layout',
      'Simplify3D, RepetierHost',
      'AutoCAD, Inventor',
    ],
    soft: ['Scrum', 'Scrum', 'GTD', 'Teamwork'],
  },
};
